apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80
    envFrom:
    - configMapRef:
        name: nginx-configmap
  restartPolicy: Never
